#!/bin/bash
IP=$(cat /etc/IP)
if [ ! -d /etc/SSHPlus/usertest ]; then
mkdir /etc/SSHPlus/usertest
fi
tput setaf 7 ; tput setab 4 ; tput bold ; printf '%30s%s%-15s\n' "Create test user" ; tput sgr0
echo ""
[ "$(ls -A /etc/SSHPlus/usertest)" ] && echo -e "\033[1;32mActive test!\033[1;37m" || echo -e "\033[1;31mNo active tests!\033[0m"
echo ""
for testeson in $(ls /etc/SSHPlus/usertest |sort |sed 's/.sh//g')
do
echo "$testeson"
done
echo ""
echo -ne "\033[1;32mUsername\033[1;37m: "; read name
if [[ -z $name ]]
then
echo ""
tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "Empty or invalid name." ; echo "" ; tput sgr0
	exit 1
fi
awk -F : ' { print $1 }' /etc/passwd > /tmp/users 
if grep -Fxq "$name" /tmp/users
then
	tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "This user already exists." ; echo "" ; tput sgr0
	exit 1
fi
echo -ne "\033[1;32mPassword\033[1;37m: "; read pass
if [[ -z $pass ]]
then
echo ""
tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "Password empty or invalid." ; echo "" ; tput sgr0
	exit 1
fi
echo -ne "\033[1;32mLimit\033[1;37m: "; read limit
if [[ -z $limit ]]
then
echo ""
tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "Empty or invalid limit." ; echo "" ; tput sgr0
	exit 1
fi
echo -ne "\033[1;32mMinutes \033[1;33m(\033[1;31mEx: \033[1;37m60\033[1;33m)\033[1;37m: "; read u_temp
if [[ -z $limit ]]
then
echo ""
tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "Empty or invalid limit." ; echo "" ; tput sgr0
	exit 1
fi
useradd -M -s /bin/false $name
(echo $pass;echo $pass) |passwd $name > /dev/null 2>&1
echo "$pass" > /etc/SSHPlus/senha/$name
echo "$name $limit" >> /root/users.db
echo "#!/bin/bash
pkill -f "$name"
userdel --force $name
grep -v ^$name[[:space:]] /root/users.db > /tmp/ph ; cat /tmp/ph > /root/users.db
rm /etc/SSHPlus/password/$name > /dev/null 2>&1
rm -rf /etc/SSHPlus/usertest/$name.sh
exit" > /etc/SSHPlus/usertest/$name.sh
chmod +x /etc/SSHPlus/usertest/$name.sh
at -f /etc/SSHPlus/usertest/$name.sh now + $u_temp min > /dev/null 2>&1
clear
echo -e "\E[44;1;37m     Test User Created     \E[0m"
echo ""
echo -e "\033[1;32mIP:\033[1;37m $IP"
echo -e "\033[1;32mUser:\033[1;37m $name"
echo -e "\033[1;32mPassword:\033[1;37m $pass"
echo -e "\033[1;32mLimit:\033[1;37m $limit"
echo -e "\033[1;32mValidity:\033[1;37m $u_temp Minutes"
echo ""
echo -e "\033[1;33mAfter the defined time the user"
echo -e "\033[1;32m$name \033[1;33mwill be disconnected and deleted.\033[0m"
exit
