#!/bin/bash
clear
echo -e "\033[1;32mDO YOU WANT TO DEPLOY THE SSHPLUS MANAGER\033[1;33m"
read -p "Do you want to remove? [y/n] " resp
if [[ "$resp" = y || "$resp" = Y ]];then
    apt-get purge screen -y > /dev/null 2>&1
    apt-get purge nmap -y > /dev/null 2>&1
    apt-get purge figlet -y > /dev/null 2>&1
    apt-get purge squid -y > /dev/null 2>&1
    apt-get purge squid3 -y > /dev/null 2>&1
    apt-get purge dropbear -y > /dev/null 2>&1
    apt-get purge apache2 -y > /dev/null 2>&1
    rm /bin/create_user /bin/expcleaner /bin/sshlimiter /bin/addhost /bin/list /bin/sshmonitor /bin/help /bin/menu /bin/OpenVPN /bin/userbackup /bin/tcpspeed /bin/badvpn /bin/optimize /bin/speedtest /bin/traffic /bin/banner /bin/limit /bin/limite /bin/passwordroot /bin/restart_services /bin/restart_system /bin/attscript /bin/create_test /bin/socks  /bin/DropBear /bin/change_limit /bin/Change_password /bin/remove /bin/details /bin/mudardata /bin/botssh /bin/infousers /bin/droplimiter /bin/connection /bin/version > /dev/null 2>&1
    rm -rf /etc/SSHPlus > /dev/null 2>&1
    clear
    echo -e "\033[1;36mThank you for using SSHPLUS MANAGER\033[1;33m"
    sleep 2
    cat /dev/null > ~/.bash_history && history -c && exit 0
else
    echo -e "\033[1;32mOk returning to the menu\033[1;33m"
    sleep 3
    menu
fi
